"""
study_config.py
===============

Every participant-facing string and the full questionnaire, in one file, so
they can be checked against the approved documents without reading any
application code.

SOURCE
------
The text below is taken from the approved documents:

    Participant_Information_Sheet_-_Omolola_Haastrup.docx
    Consent_Form_-_Omolola_Haastrup.docx
    User_Study_Questionnaire_-_Omolola_Haastrup.docx

Wording is reproduced as written, with ONE deliberate change, recorded here so
it is not lost:

    The information sheet as supplied states that data will be retained for
    FIVE years. It has been changed to TEN years, at the researcher's
    instruction, to align with University of Huddersfield policy.
    RETENTION_YEARS below is the single source of truth for that figure and is
    interpolated everywhere it appears, so the app, the information sheet and
    the debrief cannot disagree with each other.
"""

# ---------------------------------------------------------------------------
# Study identification
# ---------------------------------------------------------------------------

STUDY_TITLE = ("Evaluating Argumentation-Based Explanations for "
               "AI-Generated Temporal Plans")

PROJECT_CODE = "ECR_2024_17"

RESEARCHER_NAME = "Omolola Oluyemisi Haastrup"
RESEARCHER_EMAIL = "omololaoluyemisi.haastrup@hud.ac.uk"
SUPERVISORS = "Dr Quratul-ain Mahesar and Prof Mauro Vallati"
SCHOOL = "School of Computing and Engineering, University of Huddersfield"

# ---------------------------------------------------------------------------
# Data retention
# ---------------------------------------------------------------------------

RETENTION_YEARS = 10

RETENTION_STATEMENT = (
    f"Data will be retained for {RETENTION_YEARS} years in accordance with "
    f"the University of Huddersfield research data management policy."
)

# ---------------------------------------------------------------------------
# Participant information sheet
# ---------------------------------------------------------------------------

PARTICIPANT_INFORMATION = [
    (
        "Invitation",
        f"You are invited to take part in a research study conducted by "
        f"{RESEARCHER_NAME}, PhD researcher at the University of Huddersfield "
        f"(Project Code: {PROJECT_CODE}), supervised by {SUPERVISORS}. Before "
        f"you decide whether to take part, please read the following "
        f"information so you understand what the study involves.",
    ),
    (
        "Purpose of the study",
        "This study investigates how well people understand and can challenge "
        "explanations produced by an argumentation-based AI planning system. "
        "You will be shown a plan generated by an AI planner, along with "
        "structured explanations that justify why each action in the plan is "
        "valid or invalid. You will then answer a short questionnaire about "
        "how clear, useful, and trustworthy you found the explanation.",
    ),
    (
        "What will you be asked to do?",
        "- Read a brief introduction to the system (approximately 5 minutes).\n"
        "- Explore the plan explanation using the chatbot interface "
        "(approximately 10 to 15 minutes).\n"
        "- Complete the study questionnaire (approximately 10 minutes).\n\n"
        "**Total estimated time: 25 to 30 minutes.**",
    ),
    (
        "Do you have to take part?",
        "No. Your participation is entirely voluntary. You may withdraw at any "
        "time without giving a reason and without any negative consequences. "
        "If you withdraw, any data you have provided will be deleted.",
    ),
    (
        "Data protection and confidentiality",
        f"Your responses will be collected anonymously. No personally "
        f"identifiable information will be collected. Data will be stored "
        f"securely and used only for academic research purposes. Results will "
        f"be reported in aggregate form only. {RETENTION_STATEMENT}",
    ),
    (
        "Are there any risks or benefits?",
        "There are no anticipated risks to taking part beyond those of "
        "everyday computer use. There is no direct benefit to you, but your "
        "responses will help improve how AI planning systems explain their "
        "decisions to people.",
    ),
    (
        "Ethics approval",
        "This study has received ethical approval from the University of "
        "Huddersfield School of Computing and Engineering Ethics Committee.",
    ),
    (
        "Contact for further information",
        f"**Researcher:** {RESEARCHER_NAME}\n\n"
        f"**Email:** {RESEARCHER_EMAIL}\n\n"
        f"{SCHOOL}.\n\n"
        f"If you have any concerns about the way the study has been conducted, "
        f"you may contact the researcher's supervisor, Dr Quratul-ain Mahesar, "
        f"or the School of Computing and Engineering Ethics Committee.",
    ),
]

PIS_CLOSING = "Thank you for taking the time to read this information sheet."

# ---------------------------------------------------------------------------
# Consent
# ---------------------------------------------------------------------------

CONSENT_PREAMBLE = (
    "This consent form should be read alongside the Participant Information "
    "Sheet. By ticking the statements below you confirm your agreement to "
    "take part in the study described there."
)

#: The six approved statements, in order and unaltered. A seventh item about
#: the retention period has deliberately NOT been added, so the consent form
#: still matches what was approved. The retention period is disclosed in the
#: information sheet instead.
CONSENT_ITEMS = [
    "I have read and understood the Participant Information Sheet.",
    "I understand that my participation is voluntary and I can withdraw at "
    "any time.",
    "I understand that my responses will be anonymous and stored securely.",
    "I understand that data will be used only for academic research and "
    "reported in aggregate.",
    "I am 18 years of age or older.",
    "I consent to participate in this study.",
]

CONSENT_NOTE = ("All six statements must be confirmed before participation "
                "can proceed.")

CONSENT_TIMESTAMP_NOTE = (
    "Ticking all statements above records your consent, and the date and time "
    "are recorded automatically."
)

# ---------------------------------------------------------------------------
# Task and debrief
# ---------------------------------------------------------------------------

TASK_INTRODUCTION = (
    "On the next screen you will see a plan produced by an automated planner, "
    "and a chatbot that can explain it. The chatbot will first tell you "
    "whether the plan is valid. You can then put questions to it by choosing "
    "from the buttons shown. Only questions that make sense at that point in "
    "the conversation are offered, so the buttons will change as you go.\n\n"
    "Please ask as many or as few questions as you wish. There are no right "
    "or wrong choices. When you feel you understand the plan, or when you have "
    "no further questions, select **End dialogue** and continue to the "
    "questionnaire."
)

QUESTIONNAIRE_PREAMBLE = (
    "Thank you for exploring the argumentation-based explanation system. "
    "Please answer the following questions based on your experience with the "
    "chatbot. All responses are anonymous. For the Likert items, select the "
    "one option that best matches your view."
)

DEBRIEF = (
    "Thank you for taking part.\n\n"
    "This study examined whether explanations built from formal argumentation, "
    "delivered as a dialogue rather than as a single block of text, help "
    "people understand and challenge the plans that automated planners "
    "produce. The chatbot you used was not generating explanations freely. "
    "Every answer it gave was drawn from a formal argumentation structure "
    "computed in advance, which is why it could tell you exactly which "
    "requirement a plan failed.\n\n"
    + RETENTION_STATEMENT
)

# ---------------------------------------------------------------------------
# Questionnaire
# ---------------------------------------------------------------------------

#: Response options exactly as printed on the approved form.
LIKERT_SCALE = ["Strongly disagree", "Disagree", "Neutral", "Agree",
                "Strongly agree"]

#: (section label, [(item id, item text), ...], only_if_rejected)
#:
#: Section F is completed only where the plan explored was rejected. The app
#: knows the verdict, so it shows or hides that section automatically rather
#: than relying on the participant to read the instruction.
QUESTIONNAIRE = [
    ("A — Comprehension", [
        ("C1", "I understood why each action in the plan was included."),
        ("C2", "The explanation made clear what would happen if an action were "
               "removed or reordered."),
        ("C3", "I could follow the reasoning connecting each action to the "
               "goal."),
    ], False),
    ("B — Perceived correctness", [
        ("PC1", "The explanation accurately reflected why the plan is valid."),
        ("PC2", "The verdict (ACCEPTED / REJECTED) matched my understanding of "
                "the plan."),
    ], False),
    ("C — Contestability", [
        ("K1", "I felt I could raise a challenge against any part of the "
               "explanation I disagreed with."),
        ("K2", "The critical questions gave me a clear way to probe the plan's "
               "justification."),
    ], False),
    ("D — Transparency", [
        ("T1", "Seeing the individual premises helped me understand why the "
               "plan is valid."),
        ("T2", "I could see exactly which facts the system used to justify "
               "each claim."),
    ], False),
    ("E — Satisfaction", [
        ("SAT1", "Overall, I was satisfied with the quality of the explanation "
                 "I received."),
        ("SAT2", "I would trust a plan more if it came with this kind of "
                 "explanation."),
    ], False),
    ("F — Failure comprehension", [
        ("F1", "When the plan was rejected, I understood which condition "
               "caused the failure."),
        ("F2", "I understood what would need to change for the plan to become "
               "valid."),
    ], True),
    ("G — Dialogue engagement", [
        ("AA", "After exploring the critical questions, I was more confident "
               "in the plan's validity (or invalidity)."),
    ], False),
]

SECTION_F_NOTE = "Shown because the plan you explored was rejected."

#: Self-reported count. The app also records the TRUE count from the dialogue
#: transcript, under a separate field, so the two can be compared. The field is
#: deliberately not pre-filled, since pre-filling would destroy the
#: self-report.
COUNT_ITEM = ("DL", "How many critical questions did you click during your "
                    "session?")

OPEN_QUESTIONS = [
    ("OQ1", "What aspect of the explanation was most helpful, and why?"),
    ("OQ2", "What aspect was least helpful or most confusing?"),
    ("OQ3", "Any other comments or suggestions?"),
]

QUESTIONNAIRE_CLOSING = "Thank you for completing this questionnaire."


def sections_for(verdict=None):
    """Return the sections that apply, given the verdict shown."""
    return [(label, items) for label, items, only_if_rejected in QUESTIONNAIRE
            if not (only_if_rejected and verdict == "ACCEPTED")]


def all_items(verdict=None):
    """Flatten to (section, item id, item text).

    verdict="ACCEPTED" omits section F. verdict=None returns every item, which
    is the count to quote when describing the full instrument.
    """
    return [(label, item_id, text)
            for label, items in sections_for(verdict)
            for item_id, text in items]
